// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7EA7gbqa0VIpPSlWHjRhoNx9swjF9IiU',
    appId: '1:352987894649:web:d4953048155856b4f695a8',
    messagingSenderId: '352987894649',
    projectId: 'servicehub-a2806',
    authDomain: 'servicehub-a2806.firebaseapp.com',
    storageBucket: 'servicehub-a2806.firebasestorage.app',
    measurementId: 'G-JZG02136VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6JlK50SxkigQzUrvU-fgkdAnEPxLAjF8',
    appId: '1:352987894649:android:89dd94265a36a810f695a8',
    messagingSenderId: '352987894649',
    projectId: 'servicehub-a2806',
    storageBucket: 'servicehub-a2806.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7wVS3dCpj4QFRq0vONo8GJJr9JasnbGw',
    appId: '1:352987894649:ios:e0e54b5293ddf416f695a8',
    messagingSenderId: '352987894649',
    projectId: 'servicehub-a2806',
    storageBucket: 'servicehub-a2806.firebasestorage.app',
    iosBundleId: 'com.example.serviceHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7wVS3dCpj4QFRq0vONo8GJJr9JasnbGw',
    appId: '1:352987894649:ios:e0e54b5293ddf416f695a8',
    messagingSenderId: '352987894649',
    projectId: 'servicehub-a2806',
    storageBucket: 'servicehub-a2806.firebasestorage.app',
    iosBundleId: 'com.example.serviceHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7EA7gbqa0VIpPSlWHjRhoNx9swjF9IiU',
    appId: '1:352987894649:web:e7d2d88a3efa27faf695a8',
    messagingSenderId: '352987894649',
    projectId: 'servicehub-a2806',
    authDomain: 'servicehub-a2806.firebaseapp.com',
    storageBucket: 'servicehub-a2806.firebasestorage.app',
    measurementId: 'G-7NNZBXP47V',
  );
}
